label_to_ind = {
    'Basketball': '1',
    'BasketballDunk': '2',
    'Biking': '3',
    'CliffDiving': '4',
    'CricketBowling': '5',
    'Diving': '6',
    'Fencing': '7',
    'FloorGymnastics': '8',
    'GolfSwing': '9',
    'HorseRiding': '10',
    'IceDancing': '11',
    'LongJump': '12',
    'PoleVault': '13',
    'RopeClimbing': '14',
    'SalsaSpin': '15',
    'SkateBoarding': '16',
    'Skiing': '17',
    'Skijet': '18',
    'SoccerJuggling': '19',
    'Surfing': '20',
    'TennisSwing': '21',
    'TrampolineJumping': '22',
    'VolleyballSpiking': '23',
    'WalkingWithDog': '24'
}

ind_to_label = {
    '1': 'Basketball',
    '2': 'BasketballDunk',
    '3': 'Biking',
    '4': 'CliffDiving',
    '5': 'CricketBowling',
    '6': 'Diving',
    '7': 'Fencing',
    '8': 'FloorGymnastics',
    '9': 'GolfSwing',
    '10': 'HorseRiding',
    '11': 'IceDancing',
    '12': 'LongJump',
    '13': 'PoleVault',
    '14': 'RopeClimbing',
    '15': 'SalsaSpin',
    '16': 'SkateBoarding',
    '17': 'Skiing',
    '18': 'Skijet',
    '19': 'SoccerJuggling',
    '20': 'Surfing',
    '21': 'TennisSwing',
    '22': 'TrampolineJumping',
    '23': 'VolleyballSpiking',
    '24': 'WalkingWithDog'
}
